USE ROLE ACCOUNTADMIN;

USE DATABASE AIR_OPS;

CREATE OR REPLACE STORAGE INTEGRATION AIR_OPS_S3_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE

    STORAGE_AWS_ROLE_ARN =
        '<YOUR_ROLE_ARN>'

    STORAGE_ALLOWED_LOCATIONS =
        ('s3://airops-data-platform-adamb/');


DESC INTEGRATION AIR_OPS_S3_INT;