USE ROLE ACCOUNTADMIN;
USE DATABASE AIR_OPS;
USE SCHEMA RAW;


CREATE OR REPLACE FILE FORMAT BTS_CSV_HEADER_FORMAT
    TYPE = CSV
    PARSE_HEADER = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL')
    EMPTY_FIELD_AS_NULL = TRUE
    TRIM_SPACE = TRUE;


CREATE OR REPLACE STAGE BTS_FLIGHTS_STAGE
    URL = 's3://airops-data-platform-adamb/prepared/flights/'
    STORAGE_INTEGRATION = AIR_OPS_S3_INT
    FILE_FORMAT = BTS_CSV_HEADER_FORMAT;