USE ROLE ACCOUNTADMIN;
USE WAREHOUSE AIR_OPS_WH;
USE DATABASE AIR_OPS;
USE SCHEMA RAW;


CREATE OR REPLACE TABLE FLIGHTS
USING TEMPLATE (
    SELECT ARRAY_AGG(
        OBJECT_CONSTRUCT(*)
    )
    FROM TABLE(
        INFER_SCHEMA(
            LOCATION => '@AIR_OPS.RAW.BTS_FLIGHTS_STAGE',
            FILE_FORMAT => 'AIR_OPS.RAW.BTS_CSV_HEADER_FORMAT'
        )
    )
);

ALTER TABLE AIR_OPS.RAW.FLIGHTS
ADD COLUMN _SOURCE_FILE STRING;

ALTER TABLE AIR_OPS.RAW.FLIGHTS
ADD COLUMN _INGESTED_AT TIMESTAMP_LTZ;

ALTER TABLE AIR_OPS.RAW.FLIGHTS
ADD COLUMN _FILE_LAST_MODIFIED TIMESTAMP_LTZ;

ALTER FILE FORMAT AIR_OPS.RAW.BTS_CSV_HEADER_FORMAT
SET ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;