USE WAREHOUSE AIR_OPS_WH;


COPY INTO AIR_OPS.RAW.FLIGHTS
FROM @AIR_OPS.RAW.BTS_FLIGHTS_STAGE
FILE_FORMAT = (
    FORMAT_NAME = 'AIR_OPS.RAW.BTS_CSV_HEADER_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE

INCLUDE_METADATA = (
    _SOURCE_FILE = METADATA$FILENAME,
    _INGESTED_AT = METADATA$START_SCAN_TIME,
    _FILE_LAST_MODIFIED = METADATA$FILE_LAST_MODIFIED
)

ON_ERROR = 'ABORT_STATEMENT';

